namespace SIGE.Dashboard;

public class FakeDependenciasRepository : IDependenciasRepository
{
    private static readonly Dictionary<int, Region> _regiones = new()
    {
        { 1, new Region { Id = 1, Name = "Xalapa" } },
        { 2, new Region { Id = 2, Name = "Veracruz" } },
        { 3, new Region { Id = 3, Name = "Orizaba-Córdoba" } },
        { 4, new Region { Id = 4, Name = "Poza Rica-Tuxpan" } },
        { 5, new Region { Id = 5, Name = "Coatzacoalcos" } },
    };

    private static readonly List<Dependencia> _data =
    [
        new() { Id = 1,   Clave = "11102",   Name = "Facultad de Ingeniería Civil",                                                                      FkIdRegion = 1, IsActive = true },
        new() { Id = 2,   Clave = "11103",   Name = "Facultad de Ingeniería Mecánica y Eléctrica",                                                       FkIdRegion = 1, IsActive = true },
        new() { Id = 3,   Clave = "11104",   Name = "Facultad de Ciencias Químicas",                                                                     FkIdRegion = 1, IsActive = true },
        new() { Id = 4,   Clave = "11105",   Name = "Facultad de Química Farmacéutica Biológica",                                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 5,   Clave = "11106",   Name = "Facultad de Física",                                                                                FkIdRegion = 1, IsActive = true },
        new() { Id = 6,   Clave = "11107",   Name = "Facultad de Matemáticas",                                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 7,   Clave = "11108",   Name = "Facultad de Arquitectura",                                                                          FkIdRegion = 1, IsActive = true },
        new() { Id = 8,   Clave = "11109",   Name = "Facultad de Instrumentación Electrónica",                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 9,   Clave = "11110",   Name = "Centro de Investigación y Desarrollo en Alimentos",                                                 FkIdRegion = 1, IsActive = true },
        new() { Id = 10,  Clave = "11112",   Name = "Instituto de Investigaciones en Inteligencia Artificial",                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 11,  Clave = "11113",   Name = "Instituto de Química Aplicada",                                                                     FkIdRegion = 1, IsActive = true },
        new() { Id = 12,  Clave = "11114",   Name = "Centro de Ciencias de la Tierra",                                                                   FkIdRegion = 1, IsActive = true },
        new() { Id = 13,  Clave = "11115",   Name = "Centro de Investigación y Desarrollo en Alimentos",                                                 FkIdRegion = 1, IsActive = true },
        new() { Id = 14,  Clave = "11201",   Name = "Facultad de Derecho",                                                                               FkIdRegion = 1, IsActive = true },
        new() { Id = 15,  Clave = "11203",   Name = "Facultad de Idiomas",                                                                               FkIdRegion = 1, IsActive = true },
        new() { Id = 16,  Clave = "11204",   Name = "Facultad de Pedagogía",                                                                             FkIdRegion = 1, IsActive = true },
        new() { Id = 17,  Clave = "11205",   Name = "Facultad de Letras Españolas",                                                                      FkIdRegion = 1, IsActive = true },
        new() { Id = 18,  Clave = "11206",   Name = "Facultad de Historia",                                                                              FkIdRegion = 1, IsActive = true },
        new() { Id = 19,  Clave = "11207",   Name = "Facultad de Filosofía",                                                                             FkIdRegion = 1, IsActive = true },
        new() { Id = 20,  Clave = "11208",   Name = "Facultad de Antropología",                                                                          FkIdRegion = 1, IsActive = true },
        new() { Id = 21,  Clave = "11209",   Name = "Facultad de Sociología",                                                                            FkIdRegion = 1, IsActive = true },
        new() { Id = 22,  Clave = "11213",   Name = "Instituto de Investigaciones Jurídicas",                                                            FkIdRegion = 1, IsActive = true },
        new() { Id = 23,  Clave = "11214",   Name = "Instituto de Investigaciones Histórico Sociales",                                                   FkIdRegion = 1, IsActive = true },
        new() { Id = 24,  Clave = "11215",   Name = "Instituto de Investigaciones Lingüístico Literarias",                                               FkIdRegion = 1, IsActive = true },
        new() { Id = 25,  Clave = "11216",   Name = "Instituto de Investigaciones en Educación",                                                         FkIdRegion = 1, IsActive = true },
        new() { Id = 26,  Clave = "11218",   Name = "Instituto de Filosofía",                                                                            FkIdRegion = 1, IsActive = true },
        new() { Id = 27,  Clave = "11219",   Name = "Centro de Estudios de la Cultura y la Comunicación",                                                FkIdRegion = 1, IsActive = true },
        new() { Id = 28,  Clave = "11221",   Name = "Centro de Estudios de Genero de la Universidad Veracruzana",                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 29,  Clave = "11301",   Name = "Facultad de Contaduría y Administración",                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 30,  Clave = "11303",   Name = "Facultad de Economía",                                                                              FkIdRegion = 1, IsActive = true },
        new() { Id = 31,  Clave = "11304",   Name = "Facultad de Estadística E Informática",                                                             FkIdRegion = 1, IsActive = true },
        new() { Id = 32,  Clave = "11305",   Name = "Instituto de Investigaciones y Estudios Superiores Económicos y Sociales",                          FkIdRegion = 1, IsActive = true },
        new() { Id = 33,  Clave = "11306",   Name = "Instituto de Investigaciones y Estudios Superiores de Las Ciencias Administrativas",                FkIdRegion = 1, IsActive = true },
        new() { Id = 34,  Clave = "11307",   Name = "Instituto de Investigaciones en Contaduría",                                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 35,  Clave = "11309",   Name = "Facultad de Ciencias Administrativas y Sociales",                                                   FkIdRegion = 1, IsActive = true },
        new() { Id = 36,  Clave = "11310",   Name = "Centro de Estudios de Opinión y Análisis de la Universidad Veracruzana",                            FkIdRegion = 1, IsActive = true },
        new() { Id = 37,  Clave = "11402",   Name = "Facultad de Medicina",                                                                              FkIdRegion = 1, IsActive = true },
        new() { Id = 38,  Clave = "11403",   Name = "Facultad de Odontología",                                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 39,  Clave = "11404",   Name = "Facultad de Bioanalisis",                                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 40,  Clave = "11405",   Name = "Facultad de Nutrición",                                                                             FkIdRegion = 1, IsActive = true },
        new() { Id = 41,  Clave = "11406",   Name = "Facultad de Enfermería",                                                                            FkIdRegion = 1, IsActive = true },
        new() { Id = 42,  Clave = "11407",   Name = "Facultad de Psicología",                                                                            FkIdRegion = 1, IsActive = true },
        new() { Id = 43,  Clave = "11408",   Name = "Instituto de Ciencias de la Salud",                                                                 FkIdRegion = 1, IsActive = true },
        new() { Id = 44,  Clave = "11409",   Name = "Instituto de Investigaciones Psicológicas",                                                         FkIdRegion = 1, IsActive = true },
        new() { Id = 45,  Clave = "11411",   Name = "Instituto de Salud Publica",                                                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 46,  Clave = "11413",   Name = "Instituto de Psicología y Educación",                                                               FkIdRegion = 1, IsActive = true },
        new() { Id = 47,  Clave = "11414",   Name = "Centro de Investigaciones Biomédicas",                                                              FkIdRegion = 1, IsActive = true },
        new() { Id = 48,  Clave = "11415",   Name = "Instituto de Investigaciones Cerebrales",                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 49,  Clave = "11502",   Name = "Facultad de Biología",                                                                              FkIdRegion = 1, IsActive = true },
        new() { Id = 50,  Clave = "11503",   Name = "Facultad de Ciencias Agrícolas",                                                                    FkIdRegion = 1, IsActive = true },
        new() { Id = 51,  Clave = "11504",   Name = "Instituto de Investigaciones Biológicas",                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 52,  Clave = "11505",   Name = "Instituto de Neuroetologia",                                                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 53,  Clave = "11506",   Name = "Instituto de Investigaciones Forestales",                                                           FkIdRegion = 1, IsActive = true },
        new() { Id = 54,  Clave = "11508",   Name = "Instituto de Biotecnología y Ecología Aplicada",                                                    FkIdRegion = 1, IsActive = true },
        new() { Id = 55,  Clave = "11509",   Name = "Centro de Investigaciones Tropicales",                                                              FkIdRegion = 1, IsActive = true },
        new() { Id = 56,  Clave = "11511",   Name = "Centro de Investigación en Micología Aplicada",                                                     FkIdRegion = 1, IsActive = true },
        new() { Id = 57,  Clave = "11602",   Name = "Facultad de Música",                                                                                FkIdRegion = 1, IsActive = true },
        new() { Id = 58,  Clave = "11603",   Name = "Facultad de Danza",                                                                                 FkIdRegion = 1, IsActive = true },
        new() { Id = 59,  Clave = "11604",   Name = "Facultad de Artes Plásticas",                                                                       FkIdRegion = 1, IsActive = true },
        new() { Id = 60,  Clave = "11605",   Name = "Facultad de Teatro",                                                                                FkIdRegion = 1, IsActive = true },
        new() { Id = 61,  Clave = "11606",   Name = "Instituto de Artes Plásticas",                                                                      FkIdRegion = 1, IsActive = true },
        new() { Id = 62,  Clave = "11608",   Name = "Centro de Estudios de Jazz",                                                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 63,  Clave = "11609",   Name = "Centro de Estudios, Creación y Documentación de las Artes",                                         FkIdRegion = 1, IsActive = true },
        new() { Id = 64,  Clave = "11701",   Name = "Direccion General del Sistema de Enseñanza Abierta",                                                FkIdRegion = 1, IsActive = true },
        new() { Id = 65,  Clave = "11704_1", Name = "Universidad Veracruzana Intercultural",                                                             FkIdRegion = 1, IsActive = true },
        new() { Id = 66,  Clave = "11704_3", Name = "Universidad Veracruzana Intercultural",                                                             FkIdRegion = 3, IsActive = true },
        new() { Id = 67,  Clave = "11704_4", Name = "Universidad Veracruzana Intercultural",                                                             FkIdRegion = 4, IsActive = true },
        new() { Id = 68,  Clave = "11704_5", Name = "Universidad Veracruzana Intercultural Sede Regional Selvas",                                        FkIdRegion = 5, IsActive = true },
        new() { Id = 69,  Clave = "11707",   Name = "Centro de Estudios China-veracruz",                                                                 FkIdRegion = 1, IsActive = true },
        new() { Id = 70,  Clave = "11709",   Name = "Centro de Eco Alfabetización y Dialogo de Saberes",                                                 FkIdRegion = 1, IsActive = true },
        new() { Id = 71,  Clave = "11711",   Name = "Unidad de Estudios de Posgrado",                                                                    FkIdRegion = 1, IsActive = true },
        new() { Id = 72,  Clave = "11728",   Name = "Centro de Investigación E Innovación en Educación Superior",                                        FkIdRegion = 1, IsActive = true },
        new() { Id = 73,  Clave = "21301",   Name = "Facultad de Administración",                                                                        FkIdRegion = 2, IsActive = true },
        new() { Id = 74,  Clave = "21402",   Name = "Facultad de Medicina",                                                                              FkIdRegion = 2, IsActive = true },
        new() { Id = 75,  Clave = "21403",   Name = "Facultad de Bioanalisis",                                                                           FkIdRegion = 2, IsActive = true },
        new() { Id = 76,  Clave = "21404",   Name = "Facultad de Nutrición",                                                                             FkIdRegion = 2, IsActive = true },
        new() { Id = 77,  Clave = "21405",   Name = "Facultad de Psicología",                                                                            FkIdRegion = 2, IsActive = true },
        new() { Id = 78,  Clave = "21406",   Name = "Facultad de Enfermería",                                                                            FkIdRegion = 2, IsActive = true },
        new() { Id = 79,  Clave = "21407",   Name = "Instituto de Investigaciones Médico-biológicas",                                                    FkIdRegion = 2, IsActive = true },
        new() { Id = 80,  Clave = "21501",   Name = "Facultad de Medicina Veterinaria y Zootecnia",                                                      FkIdRegion = 2, IsActive = true },
        new() { Id = 81,  Clave = "21801",   Name = "Taller Libre de Artes",                                                                             FkIdRegion = 2, IsActive = true },
        new() { Id = 82,  Clave = "22102",   Name = "Instituto de Ingeniería",                                                                           FkIdRegion = 2, IsActive = true },
        new() { Id = 83,  Clave = "22103",   Name = "Centro de Investigación en Micro y Nanotecnología",                                                 FkIdRegion = 2, IsActive = true },
        new() { Id = 84,  Clave = "22104",   Name = "Facultad de Ingeniería Eléctrica y Electrónica",                                                    FkIdRegion = 2, IsActive = true },
        new() { Id = 85,  Clave = "22105",   Name = "Facultad de Ciencias Químicas",                                                                     FkIdRegion = 2, IsActive = true },
        new() { Id = 86,  Clave = "22106",   Name = "Facultad de Ingeniería Mecánica y Ciencias Navales",                                                FkIdRegion = 2, IsActive = true },
        new() { Id = 87,  Clave = "22107",   Name = "Facultad de Ingeniería de la Construcción y el Hábitat",                                            FkIdRegion = 2, IsActive = true },
        new() { Id = 88,  Clave = "22201",   Name = "Facultad de Ciencias y Técnicas de la Comunicación",                                                FkIdRegion = 2, IsActive = true },
        new() { Id = 89,  Clave = "22202",   Name = "Facultad de Pedagogía",                                                                             FkIdRegion = 2, IsActive = true },
        new() { Id = 90,  Clave = "22302",   Name = "Facultad de Contaduría y Negocios",                                                                 FkIdRegion = 2, IsActive = true },
        new() { Id = 91,  Clave = "22401",   Name = "Facultad de Odontología",                                                                           FkIdRegion = 2, IsActive = true },
        new() { Id = 92,  Clave = "22402",   Name = "Facultad de Educación Física",                                                                      FkIdRegion = 2, IsActive = true },
        new() { Id = 93,  Clave = "22403",   Name = "Instituto de Medicina Forense",                                                                     FkIdRegion = 2, IsActive = true },
        new() { Id = 94,  Clave = "22501",   Name = "Instituto de Ciencias Marinas y Pesquerías",                                                        FkIdRegion = 2, IsActive = true },
        new() { Id = 95,  Clave = "22701",   Name = "Direccion General del Sistema de Enseñanza Abierta",                                                FkIdRegion = 2, IsActive = true },
        new() { Id = 96,  Clave = "22801",   Name = "Centro de Idiomas",                                                                                 FkIdRegion = 2, IsActive = true },
        new() { Id = 97,  Clave = "31101",   Name = "Facultad de Ciencias Químicas",                                                                     FkIdRegion = 3, IsActive = true },
        new() { Id = 98,  Clave = "31401",   Name = "Facultad de Enfermería",                                                                            FkIdRegion = 3, IsActive = true },
        new() { Id = 99,  Clave = "31701",   Name = "Coordinación Académica Regional del Sistema de Enseñanza Abierta",                                  FkIdRegion = 3, IsActive = true },
        new() { Id = 100, Clave = "31801",   Name = "Centro de Idiomas",                                                                                 FkIdRegion = 3, IsActive = true },
        new() { Id = 101, Clave = "32101",   Name = "Facultad de Arquitectura",                                                                          FkIdRegion = 3, IsActive = true },
        new() { Id = 102, Clave = "32801",   Name = "Centro de Idiomas",                                                                                 FkIdRegion = 3, IsActive = true },
        new() { Id = 103, Clave = "32802",   Name = "Taller Libre de Artes",                                                                             FkIdRegion = 3, IsActive = true },
        new() { Id = 104, Clave = "33101",   Name = "Facultad de Ingeniería",                                                                            FkIdRegion = 3, IsActive = true },
        new() { Id = 105, Clave = "33401",   Name = "Facultad de Medicina",                                                                              FkIdRegion = 3, IsActive = true },
        new() { Id = 106, Clave = "34301",   Name = "Facultad de Negocios y Tecnologías",                                                                FkIdRegion = 3, IsActive = true },
        new() { Id = 107, Clave = "35501",   Name = "Facultad de Ciencias Biológicas y Agropecuarias",                                                   FkIdRegion = 3, IsActive = true },
        new() { Id = 108, Clave = "36401",   Name = "Facultad de Odontología",                                                                           FkIdRegion = 3, IsActive = true },
        new() { Id = 109, Clave = "41101",   Name = "Facultad de Ingeniería Civil",                                                                      FkIdRegion = 4, IsActive = true },
        new() { Id = 110, Clave = "41102",   Name = "Facultad de Ciencias Químicas",                                                                     FkIdRegion = 4, IsActive = true },
        new() { Id = 111, Clave = "41103",   Name = "Facultad de Arquitectura",                                                                          FkIdRegion = 4, IsActive = true },
        new() { Id = 112, Clave = "41104",   Name = "Facultad de Ingeniería Mecánica y Eléctrica",                                                       FkIdRegion = 4, IsActive = true },
        new() { Id = 113, Clave = "41105",   Name = "Facultad de Ingeniería Electrónica y Comunicaciones",                                               FkIdRegion = 4, IsActive = true },
        new() { Id = 114, Clave = "41201",   Name = "Facultad de Pedagogía",                                                                             FkIdRegion = 4, IsActive = true },
        new() { Id = 115, Clave = "41202",   Name = "Facultad de Trabajo Social",                                                                        FkIdRegion = 4, IsActive = true },
        new() { Id = 116, Clave = "41402",   Name = "Facultad de Medicina",                                                                              FkIdRegion = 4, IsActive = true },
        new() { Id = 117, Clave = "41403",   Name = "Facultad de Odontología",                                                                           FkIdRegion = 4, IsActive = true },
        new() { Id = 118, Clave = "41404",   Name = "Facultad de Psicología",                                                                            FkIdRegion = 4, IsActive = true },
        new() { Id = 119, Clave = "41405",   Name = "Facultad de Enfermería",                                                                            FkIdRegion = 4, IsActive = true },
        new() { Id = 120, Clave = "41701",   Name = "Direccion General del Sistema de Enseñanza Abierta",                                                FkIdRegion = 4, IsActive = true },
        new() { Id = 121, Clave = "42301",   Name = "Facultad de Contaduría",                                                                            FkIdRegion = 4, IsActive = true },
        new() { Id = 122, Clave = "42501",   Name = "Facultad de Ciencias Biológicas y Agropecuarias",                                                   FkIdRegion = 4, IsActive = true },
        new() { Id = 123, Clave = "43801",   Name = "Taller Libre de Artes",                                                                             FkIdRegion = 4, IsActive = true },
        new() { Id = 124, Clave = "51101",   Name = "Facultad de Ingeniería",                                                                            FkIdRegion = 5, IsActive = true },
        new() { Id = 125, Clave = "51102",   Name = "Facultad de Ciencias Químicas",                                                                     FkIdRegion = 5, IsActive = true },
        new() { Id = 126, Clave = "51301",   Name = "Facultad de Contaduría y Administración",                                                           FkIdRegion = 5, IsActive = true },
        new() { Id = 127, Clave = "51401",   Name = "Escuela de Enfermería",                                                                             FkIdRegion = 5, IsActive = true },
        new() { Id = 128, Clave = "51701",   Name = "Direccion General del Sistema de Enseñanza Abierta",                                                FkIdRegion = 5, IsActive = true },
        new() { Id = 129, Clave = "51703",   Name = "Centro de Investigación en Recursos Energéticos y Sustentables",                                    FkIdRegion = 5, IsActive = true },
        new() { Id = 130, Clave = "51801",   Name = "Centro de Idiomas",                                                                                 FkIdRegion = 5, IsActive = true },
        new() { Id = 131, Clave = "51803",   Name = "Taller Libre de Artes",                                                                             FkIdRegion = 5, IsActive = true },
        new() { Id = 132, Clave = "52201",   Name = "Facultad de Trabajo Social",                                                                        FkIdRegion = 5, IsActive = true },
        new() { Id = 133, Clave = "52402",   Name = "Facultad de Odontología",                                                                           FkIdRegion = 5, IsActive = true },
        new() { Id = 134, Clave = "52403",   Name = "Facultad de Medicina",                                                                              FkIdRegion = 5, IsActive = true },
        new() { Id = 135, Clave = "52404",   Name = "Facultad de Enfermería",                                                                            FkIdRegion = 5, IsActive = true },
        new() { Id = 136, Clave = "53501",   Name = "Facultad de Ingeniería en Sistemas de Producción Agropecuarias",                                    FkIdRegion = 5, IsActive = true },
    ];

    public Task<IEnumerable<Dependencia>> GetActiveAsync()
    {
        var result = _data
            .Where(d => d.IsActive)
            .OrderBy(d => d.Clave)
            .Select(d => { d.Region = _regiones[d.FkIdRegion]; return d; });

        return Task.FromResult<IEnumerable<Dependencia>>(result);
    }
}
